### ISSUE TITLE
文档Timeline交互体验优化

### ISSUE THREAD

**Issue by ocean-gao** [WeBankFinTech/fes-design#421]
### Related problem

1. 目录统一最多二级
2. 案例，一个标题一个play，不要一个标题，多个play，容易有歧义，还以为是文档渲染异常
3. 多个案例合并在一起，横向对齐，纵向对齐，中间对齐，分模块按配置项不同可以看不同效果。

**Comment by izumiiAoba** [comment]
fixed in #422
