### ISSUE TITLE
space组件实现优化，使用 gap 属性实现间距

### ISSUE THREAD

**Issue by ocean-gao** [WeBankFinTech/fes-design#453]
### Related problem

目前是margin和padding布局，实现上不够优雅

**Comment by 1zumii** [comment]
等行内浏览器兼容性升级后再重构，`gap` 属性在 Flex 布局中的[兼容性](https://developer.mozilla.org/zh-CN/docs/Web/CSS/gap#%E6%B5%8F%E8%A7%88%E5%99%A8%E5%85%BC%E5%AE%B9%E6%80%A7) chrome 要求 84 以上
