### ISSUE TITLE
table组件，右边有固定列，左边没有固定列的时候，左边滚动条没有阴影

### ISSUE THREAD

**Issue by ocean-gao** [WeBankFinTech/fes-design#461]
### Describe the bug

把右边的固定列去掉时候，左边滚动条就有阴影了。
左边固定列的情况没有验证，但可能也有这个问题。

### Expected behavior

仅左边或者仅右边有固定列，阴影展示正常

### Version

Version: 0.8.7

**Comment by 1zumii** [comment]
仅有一侧有固定列时，固定列的对侧滚动时没有阴影
<img width="827" alt="image" src="https://github.com/WeBankFinTech/fes-design/assets/39220621/019af8c2-9d11-4395-a935-9b4ee5282421">
<img width="822" alt="image" src="https://github.com/WeBankFinTech/fes-design/assets/39220621/7080dacd-ddc1-4768-8f18-1bb50e412fb5">
