### ISSUE TITLE
draggable组件设置disabled为true时代码报错

### ISSUE THREAD

**Issue by huanghaiyang** [WeBankFinTech/fes-design#485]
### 问题描述

![image](https://github.com/WeBankFinTech/fes-design/assets/5448818/990f3713-2343-41e3-85f2-6f1bd1568765)

### 如何复现

<FDraggable :disabled="true" />

### 预期结果

不报错

### 环境描述/版本信息

windows
chrome 117
node 16

**Comment by ocean-gao** [comment]
实际验证无复现，暂时先关闭了，需要进一步描述下操作步骤和操作场景，谢谢。
