### ISSUE TITLE
抽屉组件，拖拽功能，应该设置最小宽度，要不然会拖拽到没有

### ISSUE THREAD

**Issue by ocean-gao** [WeBankFinTech/fes-design#541]
### 问题描述

![image](https://github.com/WeBankFinTech/fes-design/assets/73287541/aaa1f807-c4bb-43c6-aafe-aa5cb7bf05b0)

### 预期结果

设置最小宽度

### 环境描述/版本信息

0.8.19

**Comment by 1zumii** [comment]
需要限制可拖拽的最大尺寸
