### ISSUE TITLE
Table组件，Column 配置项  ellipsis 导出类型不对

### ISSUE THREAD

**Issue by ocean-gao** [WeBankFinTech/fes-design#580]
### 问题描述

![企业微信截图_df25de66-77c7-4744-95bd-75697a21b55d](https://github.com/WeBankFinTech/fes-design/assets/73287541/2dc8a7de-554a-4f96-b899-6cd2c8812f36)

### 预期结果

导出类型正常，应该是 boolean类型，而不是现在的 false类型。

### 环境描述/版本信息

0.8.22

**Comment by 1zumii** [comment]
直接使用 columns 配置，类型正常
<img width="981" alt="image" src="https://github.com/WeBankFinTech/fes-design/assets/39220621/0444c4eb-87db-4dbf-a17d-a32fff832a91">

**Comment by 1zumii** [comment]
问题出在 `ExtractPublicPropTypes`，需要梳理下逻辑
