### ISSUE TITLE
Upload组件，自定义上传demo 代码逻辑确认是否简洁

### ISSUE THREAD

**Issue by ocean-gao** [WeBankFinTech/fes-design#584]
### 问题描述

![image](https://github.com/WeBankFinTech/fes-design/assets/73287541/35b16dbe-fc0d-44b6-871a-a4e723494a0a)

### 预期结果

确认这样写是否简洁，若不简洁，按最简单的实现逻辑进行修改

### 环境描述/版本信息

0.8.22

**Comment by 1zumii** [comment]
经二次确认，demo 中的写法是必要的，可供使用组件时参考。
