### ISSUE TITLE
FRate组件，不传v-model，渲染异常

### ISSUE THREAD

**Issue by ocean-gao** [WeBankFinTech/fes-design#642]
### 问题描述

只有传了v-model才能正常渲染，这个是有问题的。

### 预期结果

不管传不传v-model，都要支持正常渲染

### 环境描述/版本信息

0/8.31

**Comment by 1zumii** [comment]
#### 顺手修改
组件导出的 `Props` 类型，使用统一的 `ExtractPublicPropTypes`
<img width="421" alt="企业微信截图_70a9837b-09f6-45f6-9db0-2f788532fd60" src="https://github.com/WeBankFinTech/fes-design/assets/39220621/cc3e4ddf-f822-47c1-b93d-6141e002c7c8">
<img width="708" alt="企业微信截图_c7f22e85-658b-4f27-ae3f-bbd111147a87" src="https://github.com/WeBankFinTech/fes-design/assets/39220621/08fd8acc-c5a5-4f90-9f74-1afa8fc4c21d">

**Comment by 1zumii** [comment]
fixed in #672
