### ISSUE TITLE
FormItem， 支持 disalbed 配置项

### ISSUE THREAD

**Issue by ocean-gao** [WeBankFinTech/fes-design#808]
### 相关的问题

默认 undefined，如果有传值，优先级高于 form 的 disabled选项

**Comment by brizer** [comment]
我是抖音、哔哩哔哩、头条、微信视频号技术工具up主brizer，看到你的产品很好，想给你做个帮推，需要的话加vx：brizer1992，备注产品名。一到两位数rmb换四位到五位数曝光量。
